### ISSUE TITLE
Missing pages in archive

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2015#4]
Je sais pas pourquoi mais il manque des pages de conférences kindof random. 

Exemples (on dirait que c'est surtout jeudi et vendredi) ;

http://2015.webaquebec.org/activite/developpement-web-moderne-methodes-de-travail-et-principes-eprouves/
http://2015.webaquebec.org/activite/geographie-et-commerce-electronique-marche-local-ou-global-clientele-de-masse-ou-de-niche-visite-en-magasin-ou-livraison/
http://2015.webaquebec.org/activite/l-apport-du-bodystorming-dans-les-activites-d-ideation-de-la-phase-initiale-de-conception-en-design-d-interaction/
http://2015.webaquebec.org/activite/profession-sniper-technologique-viser-juste-environnements-hostiles/

**Comment by ctibo** [comment]
Vite comme ça, je ne saurais dire pourquoi. 
Ce qu'on voit sur _2015.webaquebec.org_, c'est une version statique ? 

Je ne sais pas si ça peut avoir un lien, mais dans la grille du mercredi, les url sur les activités commencent par `activites/...`, tansdis que pour celles du jeudi et vendredi, les url commencent par `http://webaquebec.org/activites/...`

Néanmoins, certains url commençant par `webaquebec.org` sont correctement redirigés vers `2015.webaquebec.org`, et d'autres non.

**Comment by j15e** [comment]
Salut Charles, désolé je voulais pas te déranger pour ça c'est juste une note pour moi-même en fait! 

Mais oui dans le fond j'ai créé une archive / copie statique du site web que j'ai poussé sur github pages (sur la branche gh-pages de ce repo) pour l'héberger gratuitement et sans BD. 

Merci du hint c'est probablement lié à ça le problème, j'ai peut-être scrapé une version dynamique de 2015.webaquebec.org mais que les pages d'horaire de jeudi/vendredi ne fonctionnait pas parce qu'on avait déjà mis une page temporaire pour 2016.

**Comment by j15e** [comment]
Fixed
